AWSTemplateFormatVersion: 2010-09-09
Description: Amazon SageMaker notebook instance.

Parameters:
  DeploymentName:
    Description: Name of the SageMaker deployment to launch this notebook to
    Type: String

  InstanceType:
    Description: The type of ML compute instance to launch for the notebook
    Type: String
    Default: ml.t3.large
    AllowedValues:
      - ml.t3.large
      - ml.t3.xlarge
      - ml.t3.2xlarge
      - ml.m5.large
      - ml.m5.xlarge
      - ml.m5.2xlarge
      - ml.m5.4xlarge
      - ml.m5.12xlarge
      - ml.m5.24xlarge

Resources:
  NotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      DirectInternetAccess: Enabled
      SubnetId: subnet-052cd77bfd8cec71f
      NotebookInstanceName: !Sub '${AWS::StackName}'
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - Fn::ImportValue: !Sub 'sagemaker-${DeploymentName}-infra-notebook-sg'
      RoleArn:
        Fn::ImportValue: !Sub 'sagemaker-${DeploymentName}-iam-notebook-role-arn'
      Tags:
        - { Key: Name, Value: !Sub '${AWS::StackName}' }
        - { Key: DeploymentName, Value: !Ref DeploymentName }
